# Altered .travis.yml
#
# Base and info here:
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Choose a build environment
dist: xenial

language: haskell

# Caching so the next build will be fast too.
cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.0.2

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# install stack
- curl -sSL https://get.haskellstack.org/ | sh

install:
# Build dependencies
- stack --version
- stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

script:
# Build the package, its tests, and its docs and run the tests
- stack --no-terminal test --system-ghc

notifications:
  email: false
